name: Test
on:
  push:
    branches:
          - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.0'

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: install deps
        run: poetry install

      - name: test
        run: ./test_run.sh
